//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PROYECTO_PAQUETERIA_DIARS.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PROYECTO_PAQUETERIA_DIARS.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _080eb9d6_5405_4974_b7b1_bcd83c5ab64c {
            get {
                object obj = ResourceManager.GetObject("080eb9d6-5405-4974-b7b1-bcd83c5ab64c", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _080eb9d6_5405_4974_b7b1_bcd83c5ab64c1 {
            get {
                object obj = ResourceManager.GetObject("080eb9d6-5405-4974-b7b1-bcd83c5ab64c1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _2481723 {
            get {
                object obj = ResourceManager.GetObject("2481723", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _3830ceea01445409feb858e8c601e79d {
            get {
                object obj = ResourceManager.GetObject("3830ceea01445409feb858e8c601e79d", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _4998821 {
            get {
                object obj = ResourceManager.GetObject("4998821", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _5040050 {
            get {
                object obj = ResourceManager.GetObject("5040050", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _52811f98_ea96_44fe_a496_f6e59a7e8c6d {
            get {
                object obj = ResourceManager.GetObject("52811f98-ea96-44fe-a496-f6e59a7e8c6d", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _52811f98_ea96_44fe_a496_f6e59a7e8c6d1 {
            get {
                object obj = ResourceManager.GetObject("52811f98-ea96-44fe-a496-f6e59a7e8c6d1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _554795 {
            get {
                object obj = ResourceManager.GetObject("554795", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _5942b881_ae8b_426a_b707_772d10f7a15c {
            get {
                object obj = ResourceManager.GetObject("5942b881-ae8b-426a-b707-772d10f7a15c", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _5942b881_ae8b_426a_b707_772d10f7a15c__1_ {
            get {
                object obj = ResourceManager.GetObject("5942b881-ae8b-426a-b707-772d10f7a15c (1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _68d89367_ca5a_4c2b_aa1d_eb09a02e9e1e {
            get {
                object obj = ResourceManager.GetObject("68d89367-ca5a-4c2b-aa1d-eb09a02e9e1e", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _75863 {
            get {
                object obj = ResourceManager.GetObject("75863", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _9996526ae3c3dd2b4e6ad6eb78e7e03b {
            get {
                object obj = ResourceManager.GetObject("9996526ae3c3dd2b4e6ad6eb78e7e03b", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Black_Modern_Geometric_Gaming_Logo {
            get {
                object obj = ResourceManager.GetObject("Black Modern Geometric Gaming Logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Black_Modern_Geometric_Gaming_Logo1 {
            get {
                object obj = ResourceManager.GetObject("Black Modern Geometric Gaming Logo1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Captura_de_pantalla_2022_11_12_185602 {
            get {
                object obj = ResourceManager.GetObject("Captura de pantalla 2022-11-12 185602", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap depositphotos_484375014_stock_illustration_allowance_of_weightage_for_international_removebg_preview {
            get {
                object obj = ResourceManager.GetObject("depositphotos_484375014-stock-illustration-allowance-of-weightage-for-internation" +
                        "al-removebg-preview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap diavehiculo {
            get {
                object obj = ResourceManager.GetObject("diavehiculo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap download_removebg_preview__8_ {
            get {
                object obj = ResourceManager.GetObject("download-removebg-preview (8)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap download_removebg_preview__8_1 {
            get {
                object obj = ResourceManager.GetObject("download-removebg-preview (8)1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap fondo_formulario {
            get {
                object obj = ResourceManager.GetObject("fondo-formulario", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icono_de_lista_mantenimiento_comprobación_coches_vector_195510702_removebg_preview {
            get {
                object obj = ResourceManager.GetObject("icono-de-lista-mantenimiento-comprobación-coches-vector-195510702-removebg-previe" +
                        "w", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap iconos_de_calendario_y_reloj_icono_aislado_ilustración_vectorial_194001239_removebg_preview {
            get {
                object obj = ResourceManager.GetObject("iconos-de-calendario-y-reloj-icono-aislado-ilustración-vectorial-194001239-remove" +
                        "bg-preview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap images_removebg_preview__3_ {
            get {
                object obj = ResourceManager.GetObject("images-removebg-preview (3)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap images_removebg_preview__3_1 {
            get {
                object obj = ResourceManager.GetObject("images-removebg-preview (3)1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap istockphoto_1304219430_170667a_removebg_preview__1_ {
            get {
                object obj = ResourceManager.GetObject("istockphoto-1304219430-170667a-removebg-preview (1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap png_clipart_computer_icons_mask_anonymous_anonymous_mask_face_people_removebg_preview {
            get {
                object obj = ResourceManager.GetObject("png-clipart-computer-icons-mask-anonymous-anonymous-mask-face-people-removebg-pre" +
                        "view", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap png_clipart_money_bag_currency_symbol_finance_money_bag_sign_commerce_removebg_preview {
            get {
                object obj = ResourceManager.GetObject("png-clipart-money-bag-currency-symbol-finance-money-bag-sign-commerce-removebg-pr" +
                        "eview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap png_clipart_technology_roadmap_business_road_map_internet_element_angle_text_removebg_preview {
            get {
                object obj = ResourceManager.GetObject("png-clipart-technology-roadmap-business-road-map-internet-element-angle-text-remo" +
                        "vebg-preview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Trasportes_torres_ima {
            get {
                object obj = ResourceManager.GetObject("Trasportes torres ima", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Trasportes_torres_ima1 {
            get {
                object obj = ResourceManager.GetObject("Trasportes torres ima1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap WhatsApp_Image_2022_11_12_at_5_59_25_PM__1_ {
            get {
                object obj = ResourceManager.GetObject("WhatsApp Image 2022-11-12 at 5.59.25 PM (1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap WhatsApp_Image_2022_11_12_at_5_59_40_PM__2_ {
            get {
                object obj = ResourceManager.GetObject("WhatsApp Image 2022-11-12 at 5.59.40 PM (2)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap WhatsApp_Image_2022_11_12_at_5_591 {
            get {
                object obj = ResourceManager.GetObject("WhatsApp Image 2022-11-12 at 5.591", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap WhatsApp_Image_2022_11_12_at_5_592 {
            get {
                object obj = ResourceManager.GetObject("WhatsApp Image 2022-11-12 at 5.592", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
